main: es.narutocraft.authcore.AuthCore
name: AuthCore
author: "Nasgar Development"
description: "AuthCore for Narutocraft server"
version: ${project.version}

softdepend:
    - PlaceholderAPI

commands:
    core:
    setspawn:

