main: es.narutocraft.authcore.AuthPlugin
name: AuthCore
author: "Nasgar Development Team"
description: "AuthCore for Narutocraft server"
version: ${project.version}

softdepend:
    - PlaceholderAPI

commands:
    setspawn:

